// Code generated by mockery v2.46.3. DO NOT EDIT.

package accountsummary

import (
	model "stori/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionsReader is an autogenerated mock type for the TransactionsReader type
type MockTransactionsReader struct {
	mock.Mock
}

type MockTransactionsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionsReader) EXPECT() *MockTransactionsReader_Expecter {
	return &MockTransactionsReader_Expecter{mock: &_m.Mock}
}

// ReadTransactions provides a mock function with given fields:
func (_m *MockTransactionsReader) ReadTransactions() ([]model.Transaction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTransactions")
	}

	var r0 []model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Transaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionsReader_ReadTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTransactions'
type MockTransactionsReader_ReadTransactions_Call struct {
	*mock.Call
}

// ReadTransactions is a helper method to define mock.On call
func (_e *MockTransactionsReader_Expecter) ReadTransactions() *MockTransactionsReader_ReadTransactions_Call {
	return &MockTransactionsReader_ReadTransactions_Call{Call: _e.mock.On("ReadTransactions")}
}

func (_c *MockTransactionsReader_ReadTransactions_Call) Run(run func()) *MockTransactionsReader_ReadTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionsReader_ReadTransactions_Call) Return(_a0 []model.Transaction, _a1 error) *MockTransactionsReader_ReadTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionsReader_ReadTransactions_Call) RunAndReturn(run func() ([]model.Transaction, error)) *MockTransactionsReader_ReadTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionsReader creates a new instance of MockTransactionsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionsReader {
	mock := &MockTransactionsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
