name: 'cd'
on:
  workflow_run:
    workflows: ["ci"]
    branches: [main]
    types:
      - completed
jobs:
  aws-lambda:
    name: AWS lambda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.23.2
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
        cache: true
    - name: Build
      run: make aws-lambda
    - name: Deploy
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: stori
        zip_file: stori.zip
